'use client';
import React, { useState, useEffect } from 'react';
import {
  CallParticipantsList,
  CallStatsButton,
  CallingState,
  PaginatedGridLayout,
  SpeakerLayout,
  useCallStateHooks,
  ToggleAudioPublishingButton,
  ToggleVideoPublishingButton,
  ScreenShareButton,
  useCall,
} from '@stream-io/video-react-sdk';
import { useRouter, useSearchParams } from 'next/navigation';
import { Users, SquaresFour, GridFour, Monitor } from '@phosphor-icons/react';
import { Dock, DockIcon } from '@/components/ui/dock';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from './ui/dropdown-menu';

import Loader from './Loader';
import EndCallButton from './EndCallButton';
import { cn } from '@/lib/utils';
import { NoiseTexture } from '@/components/ui/noise-texture';
import MeetingHeader from './MeetingHeader';
import { Ripple } from './ui/ripple';

// Our beautiful custom fallback that perfectly mimics the MeetingSetup off-cam screen
const CustomVideoFallback = React.forwardRef<HTMLDivElement, { participant?: any }>((props, ref) => {
  const { participant } = props;
  return (
    <div ref={ref} className="w-full h-full bg-[#F8F9FB] flex items-center justify-center relative overflow-hidden">
      <Ripple 
        mainCircleSize={180} 
        numCircles={5} 
        className="opacity-20"
      />
      
      {participant?.image ? (
        <div className="relative group/avatar">
          <img 
            src={participant.image} 
            alt={participant?.name || 'User'}
            className="w-32 h-32 rounded-full object-cover relative z-10 border-4 border-white shadow-xl"
          />
          <div className="absolute inset-0 bg-primary/10 blur-2xl rounded-full scale-75 animate-pulse" />
        </div>
      ) : (
        <div className="w-32 h-32 rounded-full bg-primary/10 flex items-center justify-center text-primary text-5xl font-bold relative z-10 border-4 border-white shadow-xl">
          {participant?.name?.[0] || 'U'}
        </div>
      )}
    </div>
  );
});
CustomVideoFallback.displayName = 'CustomVideoFallback';

type CallLayoutType = 'grid' | 'fullscreen';

const MeetingRoom = () => {
  const searchParams = useSearchParams();
  const isPersonalRoom = !!searchParams.get('personal');
  const router = useRouter();
  const [layout, setLayout] = useState<CallLayoutType>('grid');
  const [showParticipants, setShowParticipants] = useState(false);
  const { useCallCallingState } = useCallStateHooks();
  const call = useCall();
  const [timeStr, setTimeStr] = useState('');

  useEffect(() => {
    const update = () => {
      const n = new Date();
      let h = n.getHours();
      const m = n.getMinutes().toString().padStart(2, '0');
      const ampm = h >= 12 ? 'PM' : 'AM';
      h = h % 12 || 12;
      setTimeStr(`${h}:${m} ${ampm}`);
    };
    update();
    const t = setInterval(update, 1000);
    return () => clearInterval(t);
  }, []);

  useEffect(() => {
    // Dirty DOM hack: Stream's server caches user IDs for guests connecting via instant meetings.
    // This forcibly replaces long "user_*" IDs with the beautiful displayName from MeetingSetup localStorage.
    const customName = typeof window !== 'undefined' ? localStorage.getItem('streamDisplayName') : null;
    
    // Fallback if null, just call them Participant to remove ugliness
    const defaultName = customName || 'Participant';

    const interval = setInterval(() => {
      if (typeof document === 'undefined') return;
      const nameNodes = document.querySelectorAll('.str-video__participant-details__name');
      
      nameNodes.forEach(node => {
        const text = node.textContent?.trim() || '';
        // If it looks like a Stream autogenerated ID, or length is unusually long (> 20), replace it!
        if (text.startsWith('user_') || (text.length > 20 && !text.includes(' '))) {
          node.textContent = defaultName;
        }
      });
    }, 300); // Fast interval to prevent flickering

    return () => clearInterval(interval);
  }, []);

  // for more detail about types of CallingState see: https://getstream.io/video/docs/react/ui-cookbook/ringing-call/#incoming-call-panel
  const callingState = useCallCallingState();

  if (callingState !== CallingState.JOINED) return <Loader />;

  const CallLayout = () => {
    switch (layout) {
      case 'grid':
        return <PaginatedGridLayout groupSize={9} VideoPlaceholder={CustomVideoFallback as any} />;
      case 'fullscreen':
      default:
        return <SpeakerLayout participantsBarPosition="right" VideoPlaceholder={CustomVideoFallback as any} />;
    }
  };

  return (
    <section className="h-screen w-full overflow-hidden bg-[#f8fafc] text-slate-900 flex flex-col font-heading relative">
      <NoiseTexture className="opacity-[0.12]" />
      <div
        className="absolute inset-0 z-0 pointer-events-none opacity-50"
        style={{
          backgroundImage: `linear-gradient(to right, #c4cccc 1px, transparent 1px), linear-gradient(to bottom, #c4cccc 1px, transparent 1px)`,
          backgroundSize: '40px 40px',
        }}
      />

      {/* Main Immersive Video Area - Fills remaining space */}
      <div className="relative flex-1 flex items-center justify-center px-6 pt-6 pb-4 z-10">
        <div 
          className="flex w-full h-full items-center justify-center mx-auto rounded-xl overflow-hidden border border-black/10 shadow-[inset_0_1px_0_#ffffff,_0_1px_3px_rgba(0,0,0,0.02),_0_24px_50px_-12px_rgba(0,0,0,0.06)] bg-white"
          style={{ borderWidth: '0.8px' }}
        >
          <CallLayout />
        </div>
        
        {/* Participants Sidebar Panel (slides out dynamically resizing call layout) */}
        <div
          className={cn('h-full ml-4 bg-[#ecedef] border border-black/10 shadow-lg rounded-none w-80 transition-all relative overflow-hidden', {
            'flex': showParticipants,
            'hidden': !showParticipants,
          })}
          style={{ borderWidth: '0.8px' }}
        >
          <NoiseTexture className="opacity-[0.12]" />
          <div className="p-4 h-full w-full relative z-10 flex flex-col">
            <CallParticipantsList onClose={() => setShowParticipants(false)} />
          </div>
        </div>
      </div>
      
      {/* 3. Controls Area - Full-Width Bottom Bar matching Google Meet Placement */}
      <div className="w-full flex justify-between items-center px-8 pb-6 pt-2 shrink-0 z-10 bg-transparent">
        {/* Bottom Left: Meeting Time & ID Info */}
        <div className="flex items-center gap-3 text-slate-500 font-semibold text-sm select-none">
          <span>{timeStr}</span>
          <span className="w-[1px] h-3.5 bg-slate-300" />
          <span className="font-normal tracking-wide lowercase">{call?.id}</span>
        </div>

        {/* Bottom Center: Circular Controls Dock */}
        <div className="flex items-center gap-3 [&_.str-video__call-controls__button]:bg-white [&_.str-video__call-controls__button]:border [&_.str-video__call-controls__button]:border-slate-300 [&_.str-video__call-controls__button]:text-slate-700 hover:[&_.str-video__call-controls__button]:bg-primary/10 hover:[&_.str-video__call-controls__button]:text-primary [&_.str-video__call-controls__button]:rounded-full [&_.str-video__call-controls__button]:w-11 [&_.str-video__call-controls__button]:h-11 [&_.str-video__call-controls__button]:transition-all duration-300">
          <ToggleAudioPublishingButton />
          <ToggleVideoPublishingButton />
          <ScreenShareButton />
          <EndCallButton />
        </div>

        {/* Bottom Right: Clean Layout & Sidebar Toggles */}
        <div className="flex items-center gap-3">
          {/* Layout combobox dropdown */}
          <DropdownMenu>
            <DropdownMenuTrigger className="flex h-11 w-11 items-center justify-center rounded-full bg-white hover:bg-primary/10 text-slate-700 hover:text-primary transition-all border border-slate-300 outline-none focus:outline-none shadow-sm" style={{ borderWidth: '0.8px' }}>
              <SquaresFour weight="bold" size={20} />
            </DropdownMenuTrigger>
            <DropdownMenuContent 
              className="bg-[#ecedef] border border-slate-300 text-slate-700 rounded-none shadow-lg mb-4 min-w-[200px] p-1 font-heading z-50"
              sideOffset={12}
              align="end"
              style={{ borderWidth: '0.8px' }}
            >
              <DropdownMenuItem
                className={cn(
                  "flex items-center gap-3 cursor-pointer rounded-none px-4 py-3 text-sm font-normal transition-colors",
                  layout === 'grid' ? "bg-primary/10 text-primary font-semibold" : "hover:bg-black/5 text-slate-800"
                )}
                onClick={() => setLayout('grid')}
              >
                <GridFour size={18} weight={layout === 'grid' ? "bold" : "regular"} />
                <span>Grid Layout</span>
              </DropdownMenuItem>
              <DropdownMenuSeparator className="bg-slate-300 my-0.5" />
              <DropdownMenuItem
                className={cn(
                  "flex items-center gap-3 cursor-pointer rounded-none px-4 py-3 text-sm font-normal transition-colors",
                  layout === 'fullscreen' ? "bg-primary/10 text-primary font-semibold" : "hover:bg-black/5 text-slate-800"
                )}
                onClick={() => setLayout('fullscreen')}
              >
                <Monitor size={18} weight={layout === 'fullscreen' ? "bold" : "regular"} />
                <span>Speaker Layout</span>
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>

          {/* Sidebar Toggle */}
          <button 
            className={cn(
              "flex h-11 w-11 items-center justify-center rounded-full border border-slate-300 transition-all duration-300 shadow-sm",
              showParticipants ? "bg-primary/10 text-primary border-primary/20" : "bg-white text-slate-700 hover:bg-primary/10 hover:text-primary"
            )} 
            style={{ borderWidth: '0.8px' }}
            onClick={() => setShowParticipants((prev) => !prev)}
            title="Toggle participants sidebar"
          >
            <Users weight="bold" size={20} />
          </button>
        </div>
      </div>
    </section>
  );
};

export default MeetingRoom;
